package com.procurement.nonPoc.interfaces.requisitions;

public interface IPrCreate {
    void requesterLoginPRCreate();
    void createButton();
    void purchaseType();
    void title();
    void shipToYokogawa();
    void salesOrder();
    void departmentPIC();
//    void project();
//    void wbs();
    void vendor();
    void rateContract();
    void incoterm();
    void shippingAddress();
    void billingType();
    void shippingMode();
    void billableToCustomer();
    void quotationRequiredBy();
    void expectedPOIssue();
    void expectedDelivery();
//    void buyerManager();
//    void projectManager();
    void buyerGroup();
    void checker();
    void caseMarking();
    void messageToSourcing();
    void rohsCompliance();
    void inspectionRequired();
    void oiAndTpCurrency();
    void orderIntake();
    void targetPrice();
    void warrantyRequirements();
    void priceValidity();
    void liquidatedDamages();
    void addLineRequisitionItems();
    void createItemsFile();
    void importItems();
    void notes();
    void attachments();
    void prCreate();
}